name: acronym
version: 1.6.0.10

dependencies:
  - base

library:
  exposed-modules: Acronym
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - text
    - text-manipulate

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - acronym
      - hspec
